// Dán URL Web App của Google Apps Script vào đây sau khi triển khai.
const API_URL = "PASTE_YOUR_APPS_SCRIPT_WEB_APP_URL_HERE";
let me=null, token="", activeChat="";
const $=id=>document.getElementById(id);
async function api(action,data={}){if(!API_URL.startsWith("https://"))throw Error("Bạn chưa cấu hình API_URL trong app.js");const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action,token,...data})});const j=await r.json();if(!j.ok)throw Error(j.error||"Có lỗi xảy ra");return j.data}
function msg(id,s){$(id).textContent=s}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function showApp(){ $("auth").classList.add("hidden");$("app").classList.remove("hidden");$("logout").classList.remove("hidden");$("who").textContent=me.name;$("adminTab").classList.toggle("hidden",!me.admin);loadAll()}
async function auth(action){try{const d=await api(action,{name:$("name").value,email:$("email").value,password:$("password").value});token=d.token;me=d.user;showApp()}catch(e){msg("authMsg",e.message)}}
$("register").onclick=()=>auth("register");$("login").onclick=()=>auth("login");$("logout").onclick=()=>{token="";me=null;$("app").classList.add("hidden");$("auth").classList.remove("hidden");$("logout").classList.add("hidden");$("who").textContent=""};
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));$(b.dataset.tab).classList.remove("hidden");if(b.dataset.tab==="chat")loadChats();if(b.dataset.tab==="friends")loadFriends();if(b.dataset.tab==="rewards")loadRewards();if(b.dataset.tab==="admin")loadAdmin()});
async function loadAll(){await loadFeed();await loadFriends();await loadRewards();if(me.admin)await loadAdmin()}
async function loadFeed(){try{$("posts").innerHTML=(await api("posts")).map(p=>`<div class="item"><div class="grow"><b>${esc(p.name)}</b><p>${esc(p.created)}</p><div>${esc(p.text)}</div></div></div>`).join("")}catch(e){}}
$("postBtn").onclick=async()=>{try{await api("post",{text:$("postText").value});$("postText").value="";loadFeed()}catch(e){alert(e.message)}};
async function loadFriends(){try{let d=await api("friends");$("users").innerHTML=d.users.filter(u=>u.id!==me.id).map(u=>`<div class="item"><span class="grow">${esc(u.name)}</span><button onclick="friend('${u.id}')">Kết bạn</button></div>`).join("");$("requests").innerHTML=d.requests.map(u=>`<div class="item"><span class="grow">${esc(u.name)} gửi lời mời</span><button onclick="accept('${u.id}')">Chấp nhận</button></div>`).join("")||"Không có lời mời."; $("myFriends").innerHTML=d.friends.map(u=>`<div class="item"><span class="grow">${esc(u.name)}</span><button onclick="openChat('${u.id}','${esc(u.name)}')">Nhắn tin</button></div>`).join("")||"Chưa có bạn bè."}catch(e){}}
async function friend(id){try{await api("friend",{to:id});loadFriends()}catch(e){alert(e.message)}}async function accept(id){try{await api("accept",{from:id});loadFriends()}catch(e){alert(e.message)}}
async function loadChats(){try{$("chatFriends").innerHTML=(await api("friends")).friends.map(u=>`<div class="item"><button class="secondary" onclick="openChat('${u.id}','${esc(u.name)}')">${esc(u.name)}</button></div>`).join("")}catch(e){}}
async function openChat(id,name){activeChat=id;$("messages").innerHTML=`<b>Đang trò chuyện với ${esc(name)}</b>`;try{let a=await api("messages",{with:id});$("messages").innerHTML=a.map(m=>`<div class="bubble ${m.from===me.id?"mine":""}">${esc(m.text)}<small>${esc(m.created)}</small></div>`).join("");$("messages").scrollTop=$("messages").scrollHeight}catch(e){alert(e.message)}}
$("sendBtn").onclick=async()=>{if(!activeChat)return;try{await api("message",{to:activeChat,text:$("message").value});$("message").value="";loadChatAgain()}catch(e){alert(e.message)}};function loadChatAgain(){openChat(activeChat,"bạn")}
async function loadRewards(){try{let d=await api("rewards");$("weekCount").textContent=d.count;$("weekRange").textContent=d.week;$("rewardHistory").innerHTML=d.history.map(x=>`<div class="item"><span class="grow">⭐ ${esc(x.reason||"Phiếu bé ngoan")}<p>${esc(x.created)}</p></span></div>`).join("")||"Chưa có phiếu."}catch(e){}}
async function loadAdmin(){try{let d=await api("admin");$("awardUser").innerHTML=d.users.map(u=>`<option value="${u.id}">${esc(u.name)} (${esc(u.email)})</option>`).join("");$("adminStats").innerHTML=d.stats.map(s=>`<div class="item">${esc(s.name)}: <b>${s.count}</b> phiếu</div>`).join("")}catch(e){}}
$("awardBtn").onclick=async()=>{try{await api("award",{userId:$("awardUser").value,reason:$("awardReason").value});msg("adminMsg","Đã phát phiếu.");loadAdmin();loadRewards()}catch(e){msg("adminMsg",e.message)}};
$("search").addEventListener("input",async()=>{if(me&&$("friends").classList.contains("hidden")===false)loadFriends()});
